### ISSUE TITLE
tslint as devDependency

### ISSUE THREAD

**Issue by jbreckel** [apollographql/persistgraphql#15]
Is there a reason why `tslint` is a `dependency` instead of a `devDependency`?

**Comment by stubailo** [comment]
I think it should be a devDependency, you're right!

**Comment by Poincare** [comment]
True - will fix.

**Comment by Poincare** [comment]
[Fixed here](https://github.com/apollographql/persistgraphql/commit/7425bc308d7f64d6408dab9c249f658bc8486795).
