### ISSUE TITLE
Extracting from JS fails with "unhandled promise rejection"

### ISSUE THREAD

**Issue by jlengstorf** [apollographql/persistgraphql#20]
I’m getting an error I’m not sure how to start debugging when trying to run `persistgraphql` on `gql`-tagged queries in a project:

```sh
$ persistgraphql src/client/containers/Test.js --add_typename
Using the add-typename query transformer.
(node:26286) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): GraphQLError: Syntax Error GraphQL (1:1) Unexpected <EOF>

1:
   ^

(node:26286) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I stripped down the file to make sure it wasn’t something else in my code:
```js
import { gql } from 'react-apollo';

const QueryOne = gql`
  query TestQuery($id: String) {
    test(id: $id) {
      id
      name
    }
  }
`;

export default {
  QueryOne,
};
```

After looking through the tests, I believe this _should_ work, so I’m not sure how or where this is failing. If this is a bug and not an issue with how I'm using it, I'm happy to contribute — just need a pointer to how I might start debugging.

Thanks!

**Comment by vlasenko** [comment]
@jlengstorf The command line should be:
```sh
$ persistgraphql src/client/containers/Test.js --js --add_typename --extension=js
```

Not very intuitive, right? :)

**Comment by jlengstorf** [comment]
@vlasenko Thanks for the clarification! I just submitted #21 to clarify usage in the README for newbies like me in the future. :)
