### ISSUE TITLE
Add License

### ISSUE THREAD

**Issue by happylinks** [apollographql/persistgraphql#36]
Hi, would it be possible for you to add a license file to this repo?
I saw that in the package.json it's described as MIT.

Thanks for the lib!

**Comment by Poincare** [comment]
Hm. I don't know what license this should actually be - @stubailo help?

**Comment by stubailo** [comment]
@Poincare just copy-paste the MIT license from Apollo Client.

**Comment by Poincare** [comment]
Done! Thanks for mentioning this @happylinks.

**Comment by happylinks** [comment]
Awesome! Our legal department thanks you ;)
