### ISSUE TITLE
Compatibility with apollo-client v0.7.3

### ISSUE THREAD

**Issue by mitjade** [apollographql/persistgraphql#4]
I get an error if I use apollo-client v0.7.3.

`import 'whatwg-fetch';`
`SyntaxError: Unexpected token import`

With apollo-client v0.6.0 it is ok.

**Comment by stubailo** [comment]
Odd, that code doesn't appear in this package - what's the stack trace?

**Comment by mitjade** [comment]
`[1] .../GitHunt-React/server_bundle.js:98859`
`[1] 	import 'whatwg-fetch';`
`[1] 	^^^^^^`
`[1] SyntaxError: Unexpected token import`
`[1]     at Object.exports.runInThisContext (vm.js:78:16)`
`[1]     at Module._compile (module.js:543:28)`
`[1]     at Object.Module._extensions..js (module.js:580:10)`
`[1]     at Module.load (module.js:488:32)`
`[1]     at tryModuleLoad (module.js:447:12)`
`[1]     at Function.Module._load (module.js:439:3)`
`[1]     at Module.runMain (module.js:605:10)`
`[1]     at run (bootstrap_node.js:420:7)`
`[1]     at startup (bootstrap_node.js:139:9)`
`[1]     at bootstrap_node.js:535:3`

Got this just by updating apollo-client on GitHunt-React.

**Comment by Poincare** [comment]
Ah. We briefly removed the `whatwg-fetch` polyfill within Apollo Client. I'm not sure what that has to do with this tool but could you try updating to the latest AC?

**Comment by mitjade** [comment]
Tried v0.8.1, same thing.

I get the same problem when I try to follow https://github.com/apollostack/GitHunt-React/pull/176/files when I add:
`import { PersistedQueryNetworkInterface } from 'extractgql/lib/browser'`

I guess `whatwg-fetch` is not the problem here, but it has something to do with `import` and `webpack`, will try to figure out what I'm doing wrong.

**Comment by ex0ns** [comment]
Hi,
Did you find a solution  ? 
I use Meteor and I had the same problem when trying to import `PersistedQueryNetworkInterface`, the issue seems to come from https://github.com/apollographql/apollo-client/blob/master/src/transport/networkInterface.ts#L1, it seems to be a ES6 compatibility issue, coming from one of the build tool (I did not find a (clean) solution though).

As I only wanted to test this package, what I did (hacky) was to change `var networkInterface_1 = require("apollo-client/transport/networkInterface");` to `var networkInterface_1 = require("apollo-client");` in the generated `ApolloNetworkInterface.js` 

I believe that https://github.com/apollographql/persistgraphql/pull/9 would solve this issue as `Request` is exported by `apollo-client/index.js` as opposed to `QueryAndOptions`

ex0ns

**Comment by mitjade** [comment]
Hi,

Current GitHunt-React and GitHunt-API examples still do not work for me, if I update 'apollo-client'.
Will wait for #9 to get merged and try again.

But was able to get it working with 0.6.0, by updating 'persistgraphql' to 0.2.10.

**Comment by ex0ns** [comment]
Yes,

I wonder if this is not a module issue between apollo-client which uses es2015 import and and persistgraphql which is based on commonJS imports.

I noticed that changing 'apollo-client' to 0.8.1 in devDependencies generates 
```
import 'whatwg-fetch';
import { print } from 'graphql-tag/printer';
export function printRequest(request) {```

in `node_modules/apollo-client/transport/networkInterface.js` 

Whereas 'apollo-client' 0.6 generates

```
require("whatwg-fetch");
var printer_1 = require("graphql-tag/printer");
function printRequest(request) {
```

I don't know where this come from (probably related to apollo-client) but, I think that there is definitely an issue with version of apollo-client.

ex0ns

**Comment by dotansimha** [comment]
I think that there is an issue with the compiled file `/apollo-client/transport/networkInterface.js` - is that okay that `import ...` is in use? I think is should be `require(...)`.

As a temporary workaround, add this to your Webpack loaders config:
```js
        {
          test: /node_modules\/apollo-client\/transport\/networkInterface\.js$/,
          loader: 'babel'
        },
```

**Comment by mitjade** [comment]
Should I raise an issue in "apollo-client"?

**Comment by dotansimha** [comment]
@mitjade I am not sure it related directly to apollo-client, since `import ...` is valid ES6 imports syntax. 
Maybe it can be solved if using Webpack and Babel config with es6 imports.

**Comment by dotansimha** [comment]
The actual error is thrown because this package imports from inner files of `apollo-client/.../..` (https://github.com/apollographql/persistgraphql/blob/master/src/network_interface/ApolloNetworkInterface.ts#L5) instead of loading those from the main package `apollo-client`.

**Comment by Poincare** [comment]
Those imports can now be removed because I believe Apollo Client now exports those from the main package.
