### ISSUE TITLE
Can it be used with Relay Modern?

### ISSUE THREAD

**Issue by luckydrq** [apollographql/persistgraphql#53]
Not read it deeply, just wonder can or cannot be used in Relay Modern. Thanks!

**Comment by MrSaints** [comment]
Related to https://github.com/apollographql/persistgraphql/pull/59

**Comment by luckydrq** [comment]
I've figured out how to implement `Persisted Query` using [relay-compiler](https://github.com/facebook/relay/blob/master/packages/relay-compiler/package.json). So this issue can be closed.
